name: clab

on:
  schedule:
    - cron:  "0 0 * * 0"
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@main

      - name: create base image
        run: sudo /bin/bash clab/base.sh

      - name: build gtp5g free5gc ueransim
        run: sudo /bin/bash clab/base-build.sh

      - name: build clab.img
        run: sudo /bin/bash clab/base-clab.sh

      - name: get clab docker images
        run: sudo /bin/bash clab/docker-images.sh

      - name: Push to transfer
        env:
          WXPUSHER_APPTOKEN: ${{ secrets.WXPUSHER_APPTOKEN }}
          WXPUSHER_UID: ${{ secrets.WXPUSHER_UID }}
        run: |
          bash transfer.sh wet /tmp/clab-*.img
          bash transfer.sh wet /tmp/clab-*.tar.xz
