name: open5gs.img

on:
  schedule:
    - cron:  "0 0 * * 0"
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main

      - name: Build UERANSIM
        run: sudo /bin/bash open5gs/UERANSIM.sh

      - name: Build UERANSIM.img
        run: sudo /bin/bash open5gs/UERANSIM.img.sh

      - name: Build open5gs.img
        run: sudo /bin/bash open5gs/open5gs.sh

      - name: Push to transfer
        env:
          WXPUSHER_APPTOKEN: ${{ secrets.WXPUSHER_APPTOKEN }}
          WXPUSHER_UID: ${{ secrets.WXPUSHER_UID }}
        run: |
          bash transfer.sh wet /tmp/ueransim-*.img
          bash transfer.sh wet /tmp/open5gs-*.img
